<?php
/**
 * HsmApi
 * PHP version 5
 *
 * @category Class
 * @package  sallfris\Leadball\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Swagger Leadball messaging service - OpenAPI 3.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.25.5
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.41
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace sallfris\Leadball\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Promise\PromiseInterface;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use InvalidArgumentException;
use sallfris\Leadball\Client\ApiException;
use sallfris\Leadball\Client\Configuration;
use sallfris\Leadball\Client\HeaderSelector;
use sallfris\Leadball\Client\Model\CreateHsmDto;
use sallfris\Leadball\Client\Model\Hsm;
use sallfris\Leadball\Client\Model\SubmitHsmForApprovalDto;
use sallfris\Leadball\Client\Model\UpdateHsmDto;
use sallfris\Leadball\Client\ObjectSerializer;
use stdClass;
use Symfony\Component\Filesystem\Exception\FileNotFoundException;

/**
 * HsmApi Class Doc Comment
 *
 * @category Class
 * @package  sallfris\Leadball\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class HsmApi
{
    /**
     * @var ClientInterface
     */
    protected $client;
    
    /**
     * @var Configuration
     */
    protected $config;
    
    /**
     * @var HeaderSelector
     */
    protected $headerSelector;
    
    /**
     * @param ClientInterface $client
     * @param Configuration $config
     * @param HeaderSelector $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration   $config = null,
        HeaderSelector  $selector = null
    )
    {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }
    
    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }
    
    /**
     * Operation createHsm
     *
     * Create a hsm
     *
     * @param CreateHsmDto $body Create a hsm (required)
     *
     * @return Hsm
     * @throws InvalidArgumentException
     * @throws ApiException on non-2xx response
     */
    public function createHsm($body)
    {
        [$response] = $this->createHsmWithHttpInfo($body);
        return $response;
    }
    
    /**
     * Operation createHsmWithHttpInfo
     *
     * Create a hsm
     *
     * @param CreateHsmDto $body Create a hsm (required)
     *
     * @return array of \sallfris\Leadball\Client\Model\Hsm, HTTP status code, HTTP response headers (array of strings)
     * @throws InvalidArgumentException
     * @throws ApiException on non-2xx response
     */
    public function createHsmWithHttpInfo($body)
    {
        $returnType = '\sallfris\Leadball\Client\Model\Hsm';
        $request = $this->createHsmRequest($body);
        
        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }
            
            $statusCode = $response->getStatusCode();
            
            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }
            
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string', 'integer', 'bool'])) {
                    $content = json_decode($content);
                }
            }
            
            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders(),
            ];
            
        } catch (ApiException $e) {
            if ($e->getCode() == 201) {
                $data = ObjectSerializer::deserialize(
                    $e->getResponseBody(),
                    '\sallfris\Leadball\Client\Model\Hsm',
                    $e->getResponseHeaders()
                );
                $e->setResponseObject($data);
            }
            throw $e;
        }
    }
    
    /**
     * Operation createHsmAsync
     *
     * Create a hsm
     *
     * @param CreateHsmDto $body Create a hsm (required)
     *
     * @return PromiseInterface
     * @throws InvalidArgumentException
     */
    public function createHsmAsync($body)
    {
        return $this->createHsmAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }
    
    /**
     * Operation createHsmAsyncWithHttpInfo
     *
     * Create a hsm
     *
     * @param CreateHsmDto $body Create a hsm (required)
     *
     * @return PromiseInterface
     * @throws InvalidArgumentException
     */
    public function createHsmAsyncWithHttpInfo($body)
    {
        $returnType = '\sallfris\Leadball\Client\Model\Hsm';
        $request = $this->createHsmRequest($body);
        
        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }
                    
                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }
    
    /**
     * Create request for operation 'createHsm'
     *
     * @param CreateHsmDto $body Create a hsm (required)
     *
     * @return Request
     * @throws InvalidArgumentException
     */
    protected function createHsmRequest(CreateHsmDto $body)
    {
        $resourcePath = '/hsm-templates';
        
        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['application/json']
        );
        $httpBody = $body;
        // \stdClass has no __toString(), so we should encode it manually
        if ($httpBody instanceof stdClass && $headers['Content-Type'] === 'application/json') {
            $httpBody = \GuzzleHttp\json_encode($httpBody);
        }
        
        // // this endpoint requires Bearer token
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        
        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        
        $headers = array_merge(
            $defaultHeaders,
            $headers
        );
        
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath,
            $headers,
            $httpBody
        );
    }
    
    /**
     * Operation deleteHsm
     *
     * Delete a hsm
     *
     * @param int $hsmId Hsm id to delete (required)
     *
     * @return Hsm
     * @throws InvalidArgumentException
     * @throws ApiException on non-2xx response
     */
    public function deleteHsm($hsmId)
    {
        [$response] = $this->deleteHsmWithHttpInfo($hsmId);
        return $response;
    }
    
    /**
     * Operation deleteHsmWithHttpInfo
     *
     * Delete a hsm
     *
     * @param int $hsmId Hsm id to delete (required)
     *
     * @return array of \sallfris\Leadball\Client\Model\Hsm, HTTP status code, HTTP response headers (array of strings)
     * @throws InvalidArgumentException
     * @throws ApiException on non-2xx response
     */
    public function deleteHsmWithHttpInfo($hsmId)
    {
        $returnType = '\sallfris\Leadball\Client\Model\Hsm';
        $request = $this->deleteHsmRequest($hsmId);
        
        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }
            
            $statusCode = $response->getStatusCode();
            
            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }
            
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string', 'integer', 'bool'])) {
                    $content = json_decode($content);
                }
            }
            
            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders(),
            ];
            
        } catch (ApiException $e) {
            if ($e->getCode() == 204) {
                $data = ObjectSerializer::deserialize(
                    $e->getResponseBody(),
                    '\sallfris\Leadball\Client\Model\Hsm',
                    $e->getResponseHeaders()
                );
                $e->setResponseObject($data);
            }
            throw $e;
        }
    }
    
    /**
     * Operation deleteHsmAsync
     *
     * Delete a hsm
     *
     * @param int $hsmId Hsm id to delete (required)
     *
     * @return PromiseInterface
     * @throws InvalidArgumentException
     */
    public function deleteHsmAsync($hsmId)
    {
        return $this->deleteHsmAsyncWithHttpInfo($hsmId)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }
    
    /**
     * Operation deleteHsmAsyncWithHttpInfo
     *
     * Delete a hsm
     *
     * @param int $hsmId Hsm id to delete (required)
     *
     * @return PromiseInterface
     * @throws InvalidArgumentException
     */
    public function deleteHsmAsyncWithHttpInfo($hsmId)
    {
        $returnType = '\sallfris\Leadball\Client\Model\Hsm';
        $request = $this->deleteHsmRequest($hsmId);
        
        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }
                    
                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }
    
    /**
     * Create request for operation 'deleteHsm'
     *
     * @param int $hsmId Hsm id to delete (required)
     *
     * @return Request
     * @throws InvalidArgumentException
     */
    protected function deleteHsmRequest(int $hsmId)
    {
        $resourcePath = '/hsm-templates/{hsmId}';
        $httpBody = '';
        
        $resourcePath = str_replace(
            '{' . 'hsmId' . '}',
            ObjectSerializer::toPathValue($hsmId),
            $resourcePath
        );
        
        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            []
        );
        
        // // this endpoint requires Bearer token
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        
        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        
        $headers = array_merge(
            $defaultHeaders,
            $headers
        );
        
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath,
            $headers,
            $httpBody
        );
    }
    
    /**
     * Operation findAllHsm
     *
     * Find all hsm
     *
     *
     * @return Hsm[]
     * @throws InvalidArgumentException
     * @throws ApiException on non-2xx response
     */
    public function findAllHsm()
    {
        [$response] = $this->findAllHsmWithHttpInfo();
        return $response;
    }
    
    /**
     * Operation findAllHsmWithHttpInfo
     *
     * Find all hsm
     *
     *
     * @return array of \sallfris\Leadball\Client\Model\Hsm[], HTTP status code, HTTP response headers (array of strings)
     * @throws InvalidArgumentException
     * @throws ApiException on non-2xx response
     */
    public function findAllHsmWithHttpInfo()
    {
        $returnType = '\sallfris\Leadball\Client\Model\Hsm[]';
        $request = $this->findAllHsmRequest();
        
        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }
            
            $statusCode = $response->getStatusCode();
            
            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }
            
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string', 'integer', 'bool'])) {
                    $content = json_decode($content);
                }
            }
            
            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders(),
            ];
            
        } catch (ApiException $e) {
            if ($e->getCode() == 200) {
                $data = ObjectSerializer::deserialize(
                    $e->getResponseBody(),
                    '\sallfris\Leadball\Client\Model\Hsm[]',
                    $e->getResponseHeaders()
                );
                $e->setResponseObject($data);
            }
            throw $e;
        }
    }
    
    /**
     * Operation findAllHsmAsync
     *
     * Find all hsm
     *
     *
     * @return PromiseInterface
     * @throws InvalidArgumentException
     */
    public function findAllHsmAsync()
    {
        return $this->findAllHsmAsyncWithHttpInfo()
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }
    
    /**
     * Operation findAllHsmAsyncWithHttpInfo
     *
     * Find all hsm
     *
     *
     * @return PromiseInterface
     * @throws InvalidArgumentException
     */
    public function findAllHsmAsyncWithHttpInfo()
    {
        $returnType = '\sallfris\Leadball\Client\Model\Hsm[]';
        $request = $this->findAllHsmRequest();
        
        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }
                    
                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }
    
    /**
     * Create request for operation 'findAllHsm'
     *
     *
     * @return Request
     * @throws InvalidArgumentException
     */
    protected function findAllHsmRequest()
    {
        
        $resourcePath = '/hsm-templates';
        $httpBody = '';
        
        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            []
        );
        
        // // this endpoint requires Bearer token
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        
        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        
        $headers = array_merge(
            $defaultHeaders,
            $headers
        );
        
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath,
            $headers,
            $httpBody
        );
    }
    
    /**
     * Operation findOneHsm
     *
     * Find hsm by id
     *
     * @param int $hsmId Id of hsm to return (required)
     *
     * @return Hsm
     * @throws InvalidArgumentException
     * @throws ApiException on non-2xx response
     */
    public function findOneHsm($hsmId)
    {
        [$response] = $this->findOneHsmWithHttpInfo($hsmId);
        return $response;
    }
    
    /**
     * Operation findOneHsmWithHttpInfo
     *
     * Find hsm by id
     *
     * @param int $hsmId Id of hsm to return (required)
     *
     * @return array of \sallfris\Leadball\Client\Model\Hsm, HTTP status code, HTTP response headers (array of strings)
     * @throws InvalidArgumentException
     * @throws ApiException on non-2xx response
     */
    public function findOneHsmWithHttpInfo($hsmId)
    {
        $returnType = '\sallfris\Leadball\Client\Model\Hsm';
        $request = $this->findOneHsmRequest($hsmId);
        
        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }
            
            $statusCode = $response->getStatusCode();
            
            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }
            
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string', 'integer', 'bool'])) {
                    $content = json_decode($content);
                }
            }
            
            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders(),
            ];
            
        } catch (ApiException $e) {
            if ($e->getCode() == 200) {
                $data = ObjectSerializer::deserialize(
                    $e->getResponseBody(),
                    '\sallfris\Leadball\Client\Model\Hsm',
                    $e->getResponseHeaders()
                );
                $e->setResponseObject($data);
            }
            throw $e;
        }
    }
    
    /**
     * Operation findOneHsmAsync
     *
     * Find hsm by id
     *
     * @param int $hsmId Id of hsm to return (required)
     *
     * @return PromiseInterface
     * @throws InvalidArgumentException
     */
    public function findOneHsmAsync($hsmId)
    {
        return $this->findOneHsmAsyncWithHttpInfo($hsmId)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }
    
    /**
     * Operation findOneHsmAsyncWithHttpInfo
     *
     * Find hsm by id
     *
     * @param int $hsmId Id of hsm to return (required)
     *
     * @return PromiseInterface
     * @throws InvalidArgumentException
     */
    public function findOneHsmAsyncWithHttpInfo($hsmId)
    {
        $returnType = '\sallfris\Leadball\Client\Model\Hsm';
        $request = $this->findOneHsmRequest($hsmId);
        
        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }
                    
                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }
    
    /**
     * Create request for operation 'findOneHsm'
     *
     * @param int $hsmId Id of hsm to return (required)
     *
     * @return Request
     * @throws InvalidArgumentException
     */
    protected function findOneHsmRequest(int $hsmId)
    {
        $resourcePath = '/hsm-templates/{hsmId}';
        $httpBody = '';
        
        $resourcePath = str_replace(
            '{' . 'hsmId' . '}',
            ObjectSerializer::toPathValue($hsmId),
            $resourcePath
        );
        
        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            []
        );
        
        // // this endpoint requires Bearer token
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        
        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        
        $headers = array_merge(
            $defaultHeaders,
            $headers
        );
        
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath,
            $headers,
            $httpBody
        );
    }
    
    /**
     * Operation submitHsmForApproval
     *
     * Submit hsm for approval
     *
     * @param SubmitHsmForApprovalDto $body Submit hsm for approval (required)
     * @param int $hsmId Id of hsm to return (required)
     *
     * @return void
     * @throws InvalidArgumentException
     * @throws ApiException on non-2xx response
     */
    public function submitHsmForApproval($body, $hsmId)
    {
        $this->submitHsmForApprovalWithHttpInfo($body, $hsmId);
    }
    
    /**
     * Operation submitHsmForApprovalWithHttpInfo
     *
     * Submit hsm for approval
     *
     * @param SubmitHsmForApprovalDto $body Submit hsm for approval (required)
     * @param int $hsmId Id of hsm to return (required)
     *
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws InvalidArgumentException
     * @throws ApiException on non-2xx response
     */
    public function submitHsmForApprovalWithHttpInfo($body, $hsmId)
    {
        $request = $this->submitHsmForApprovalRequest($body, $hsmId);
        
        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }
            
            $statusCode = $response->getStatusCode();
            
            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }
            
            return [null, $statusCode, $response->getHeaders()];
            
        } catch (ApiException $e) {
            error_log($e->getMessage());
            throw $e;
        }
    }
    
    /**
     * Operation submitHsmForApprovalAsync
     *
     * Submit hsm for approval
     *
     * @param SubmitHsmForApprovalDto $body Submit hsm for approval (required)
     * @param int $hsmId Id of hsm to return (required)
     *
     * @return PromiseInterface
     * @throws InvalidArgumentException
     */
    public function submitHsmForApprovalAsync($body, $hsmId)
    {
        return $this->submitHsmForApprovalAsyncWithHttpInfo($body, $hsmId)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }
    
    /**
     * Operation submitHsmForApprovalAsyncWithHttpInfo
     *
     * Submit hsm for approval
     *
     * @param SubmitHsmForApprovalDto $body Submit hsm for approval (required)
     * @param int $hsmId Id of hsm to return (required)
     *
     * @return PromiseInterface
     * @throws InvalidArgumentException
     */
    public function submitHsmForApprovalAsyncWithHttpInfo($body, $hsmId)
    {
        $request = $this->submitHsmForApprovalRequest($body, $hsmId);
        
        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }
    
    /**
     * Create request for operation 'submitHsmForApproval'
     *
     * @param SubmitHsmForApprovalDto $body Submit hsm for approval (required)
     * @param int $hsmId Id of hsm to return (required)
     *
     * @return Request
     * @throws InvalidArgumentException
     */
    protected function submitHsmForApprovalRequest(SubmitHsmForApprovalDto $body, int $hsmId)
    {
        $resourcePath = '/hsm-templates/{hsmId}/approval';
        
        $resourcePath = str_replace(
            '{' . 'hsmId' . '}',
            ObjectSerializer::toPathValue($hsmId),
            $resourcePath
        );
        
        $headers = $this->headerSelector->selectHeaders(
            [],
            ['application/json']
        );
        
        $httpBody = $body;
        // \stdClass has no __toString(), so we should encode it manually
        if ($httpBody instanceof stdClass && $headers['Content-Type'] === 'application/json') {
            $httpBody = \GuzzleHttp\json_encode($httpBody);
        }
        
        // // this endpoint requires Bearer token
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        
        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        
        $headers = array_merge(
            $defaultHeaders,
            $headers
        );
        
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath,
            $headers,
            $httpBody
        );
    }
    
    /**
     * Operation updateHsm
     *
     * Update a hsm
     *
     * @param int $hsmId Id of hsm that needs to be updated (required)
     * @param UpdateHsmDto $body Update a hsm (optional)
     *
     * @return Hsm
     * @throws InvalidArgumentException
     * @throws ApiException on non-2xx response
     */
    public function updateHsm($hsmId, $body = null)
    {
        [$response] = $this->updateHsmWithHttpInfo($hsmId, $body);
        return $response;
    }
    
    /**
     * Operation updateHsmWithHttpInfo
     *
     * Update a hsm
     *
     * @param int $hsmId Id of hsm that needs to be updated (required)
     * @param UpdateHsmDto $body Update a hsm (optional)
     *
     * @return array of \sallfris\Leadball\Client\Model\Hsm, HTTP status code, HTTP response headers (array of strings)
     * @throws InvalidArgumentException
     * @throws ApiException on non-2xx response
     */
    public function updateHsmWithHttpInfo($hsmId, $body = null)
    {
        $returnType = '\sallfris\Leadball\Client\Model\Hsm';
        $request = $this->updateHsmRequest($hsmId, $body);
        
        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }
            
            $statusCode = $response->getStatusCode();
            
            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }
            
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string', 'integer', 'bool'])) {
                    $content = json_decode($content);
                }
            }
            
            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders(),
            ];
            
        } catch (ApiException $e) {
            if ($e->getCode() == 200) {
                $data = ObjectSerializer::deserialize(
                    $e->getResponseBody(),
                    '\sallfris\Leadball\Client\Model\Hsm',
                    $e->getResponseHeaders()
                );
                $e->setResponseObject($data);
            }
            throw $e;
        }
    }
    
    /**
     * Operation updateHsmAsync
     *
     * Update a hsm
     *
     * @param int $hsmId Id of hsm that needs to be updated (required)
     * @param UpdateHsmDto $body Update a hsm (optional)
     *
     * @return PromiseInterface
     * @throws InvalidArgumentException
     */
    public function updateHsmAsync($hsmId, $body = null)
    {
        return $this->updateHsmAsyncWithHttpInfo($hsmId, $body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }
    
    /**
     * Operation updateHsmAsyncWithHttpInfo
     *
     * Update a hsm
     *
     * @param int $hsmId Id of hsm that needs to be updated (required)
     * @param UpdateHsmDto $body Update a hsm (optional)
     *
     * @return PromiseInterface
     * @throws InvalidArgumentException
     */
    public function updateHsmAsyncWithHttpInfo($hsmId, $body = null)
    {
        $returnType = '\sallfris\Leadball\Client\Model\Hsm';
        $request = $this->updateHsmRequest($hsmId, $body);
        
        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }
                    
                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }
    
    /**
     * Create request for operation 'updateHsm'
     *
     * @param int $hsmId Id of hsm that needs to be updated (required)
     * @param UpdateHsmDto|null $body Update a hsm (optional)
     *
     * @return Request
     * @throws InvalidArgumentException
     */
    protected function updateHsmRequest($hsmId, UpdateHsmDto $body = null)
    {
        
        $resourcePath = '/hsm-templates/{hsmId}';
        
        $resourcePath = str_replace(
            '{' . 'hsmId' . '}',
            ObjectSerializer::toPathValue($hsmId),
            $resourcePath
        );
        
        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['application/json']
        );
        
        $httpBody = $body;
        // \stdClass has no __toString(), so we should encode it manually
        if ($httpBody instanceof stdClass && $headers['Content-Type'] === 'application/json') {
            $httpBody = \GuzzleHttp\json_encode($httpBody);
        }
        
        // // this endpoint requires Bearer token
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        
        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        
        $headers = array_merge(
            $defaultHeaders,
            $headers
        );
        
        return new Request(
            'PATCH',
            $this->config->getHost() . $resourcePath,
            $headers,
            $httpBody
        );
    }
    
    /**
     * Create HTTP client options.
     *
     * @return array HTTP client options
     * @throws FileNotFoundException if the debug file is not found
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $debugFile = fopen($this->config->getDebugFile(), 'ab');
            if (!$debugFile) {
                throw new FileNotFoundException('Debug file not found: ' . $this->config->getDebugFile());
            }
            $options[RequestOptions::DEBUG] = $debugFile;
        }
        
        return $options;
    }
}
