<?php
/**
 * CreateMessageDto
 *
 * PHP version 5
 *
 * @category Class
 * @package  sallfris\Leadball\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Swagger Leadball messaging service - OpenAPI 3.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.25.5
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.41
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace sallfris\Leadball\Client\Model;

use ArrayAccess;
use JsonException;
use sallfris\Leadball\Client\ObjectSerializer;

/**
 * CreateMessageDto Class Doc Comment
 *
 * @category Class
 * @package  sallfris\Leadball\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CreateMessageDto implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;
    
    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $swaggerModelName = 'CreateMessageDto';
    
    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $swaggerTypes = [
        'template_id' => 'int',
        'variables' => 'object',
        'text' => 'string',
        'attachments' => '\sallfris\Leadball\Client\Model\Attachment[]',
        'buttons' => '\sallfris\Leadball\Client\Model\Button[]',
        'quoted_messages_ids' => 'int[]'];
    
    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $swaggerFormats = [
        'template_id' => null,
        'variables' => null,
        'text' => null,
        'attachments' => null,
        'buttons' => null,
        'quoted_messages_ids' => null];
    
    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }
    
    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }
    
    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'template_id' => 'templateId',
        'variables' => 'variables',
        'text' => 'text',
        'attachments' => 'attachments',
        'buttons' => 'buttons',
        'quoted_messages_ids' => 'quotedMessagesIds'];
    
    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'template_id' => 'setTemplateId',
        'variables' => 'setVariables',
        'text' => 'setText',
        'attachments' => 'setAttachments',
        'buttons' => 'setButtons',
        'quoted_messages_ids' => 'setQuotedMessagesIds'];
    
    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'template_id' => 'getTemplateId',
        'variables' => 'getVariables',
        'text' => 'getText',
        'attachments' => 'getAttachments',
        'buttons' => 'getButtons',
        'quoted_messages_ids' => 'getQuotedMessagesIds'];
    
    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }
    
    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }
    
    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }
    
    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }
    
    
    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];
    
    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['template_id'] = isset($data['template_id']) ? $data['template_id'] : null;
        $this->container['variables'] = isset($data['variables']) ? $data['variables'] : null;
        $this->container['text'] = isset($data['text']) ? $data['text'] : null;
        $this->container['attachments'] = isset($data['attachments']) ? $data['attachments'] : null;
        $this->container['buttons'] = isset($data['buttons']) ? $data['buttons'] : null;
        $this->container['quoted_messages_ids'] = isset($data['quoted_messages_ids']) ? $data['quoted_messages_ids'] : null;
    }
    
    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        return [];
    }
    
    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }
    
    
    /**
     * Gets template_id
     *
     * @return int
     */
    public function getTemplateId()
    {
        return $this->container['template_id'];
    }
    
    /**
     * Sets template_id
     *
     * @param int $templateId template_id
     *
     * @return $this
     */
    public function setTemplateId($templateId)
    {
        $this->container['template_id'] = $templateId;
        
        return $this;
    }
    
    /**
     * Gets variables
     *
     * @return object
     */
    public function getVariables()
    {
        return $this->container['variables'];
    }
    
    /**
     * Sets variables
     *
     * @param object $variables variables
     *
     * @return $this
     */
    public function setVariables($variables)
    {
        $this->container['variables'] = $variables;
        
        return $this;
    }
    
    /**
     * Gets text
     *
     * @return string
     */
    public function getText()
    {
        return $this->container['text'];
    }
    
    /**
     * Sets text
     *
     * @param string $text text
     *
     * @return $this
     */
    public function setText($text)
    {
        $this->container['text'] = $text;
        
        return $this;
    }
    
    /**
     * Gets attachments
     *
     * @return \sallfris\Leadball\Client\Model\Attachment[]
     */
    public function getAttachments()
    {
        return $this->container['attachments'];
    }
    
    /**
     * Sets attachments
     *
     * @param \sallfris\Leadball\Client\Model\Attachment[] $attachments attachments
     *
     * @return $this
     */
    public function setAttachments($attachments)
    {
        $this->container['attachments'] = $attachments;
        
        return $this;
    }
    
    /**
     * Gets buttons
     *
     * @return \sallfris\Leadball\Client\Model\Button[]
     */
    public function getButtons()
    {
        return $this->container['buttons'];
    }
    
    /**
     * Sets buttons
     *
     * @param \sallfris\Leadball\Client\Model\Button[] $buttons buttons
     *
     * @return $this
     */
    public function setButtons($buttons)
    {
        $this->container['buttons'] = $buttons;
        
        return $this;
    }
    
    /**
     * Gets quoted_messages_ids
     *
     * @return int[]
     */
    public function getQuotedMessagesIds()
    {
        return $this->container['quoted_messages_ids'];
    }
    
    /**
     * Sets quoted_messages_ids
     *
     * @param int[] $quotedMessagesIds quoted_messages_ids
     *
     * @return $this
     */
    public function setQuotedMessagesIds($quotedMessagesIds)
    {
        $this->container['quoted_messages_ids'] = $quotedMessagesIds;
        
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }
    
    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }
    
    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed $value Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }
    
    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }
    
    /**
     * Gets the string presentation of the object
     *
     * @return string
     * @throws JsonException
     */
    public function __toString(): string
    {
        $jsonOptions = defined('JSON_PRETTY_PRINT') ? JSON_PRETTY_PRINT | JSON_THROW_ON_ERROR : 0;
        
        return json_encode(ObjectSerializer::sanitizeForSerialization($this), $jsonOptions);
    }
}
